services:
  postgres:
    image: postgres:latest
    container_name: fpl_postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_MULTIPLE_DATABASES=fpl_db,airflow_db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "5433:5433"
    command: -p 5433
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -h localhost -p 5433 -U richardilemon || exit 0",
        ]
      interval: 10s
      timeout: 5s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4
    container_name: fpl_pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8082:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy

  loader:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fpl_loader
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DB_HOST=postgres
      - DB_NAME=fpl_db
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_PORT=5433
    volumes:
      # - ./scripts/db_config.py:/app/scripts
      # - ./airflow/scripts:/app/scripts

      - ./airflow/scripts:/opt/airflow/scripts

  airflow-init:
    image: apache/airflow:2.6.3
    container_name: airflow_init
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5433/airflow_db
      - AIRFLOW__CORE__FERNET_KEY=${AIRFLOW_FERNET_KEY}
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    entrypoint: /bin/bash -c "/wait-for-it.sh postgres:5433 -- airflow db init && airflow users create --username ${AIRFLOW_ADMIN_USER} --password ${AIRFLOW_ADMIN_PASSWORD} --firstname Richard --lastname Ilupeju --role Admin --email ${PGADMIN_DEFAULT_EMAIL}"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./wait-for-it.sh:/wait-for-it.sh

  airflow-webserver:
    image: apache/airflow:2.6.3
    container_name: airflow-webserver
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_started
    env_file:
      - .env
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5433/airflow_db
      - AIRFLOW__CORE__FERNET_KEY=${AIRFLOW_FERNET_KEY}
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__WEBSERVER__WEB_SERVER_PORT=8084
      - PYTHONPATH=/opt/airflow
    ports:
      - "8084:8084"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./wait-for-it.sh:/wait-for-it.sh
      - ./airflow/scripts:/opt/airflow/scripts
      # - ./db_config.py:/app/db_config.py
      - ./requirements.txt:/app/requirements.txt
    command: >
      bash -c "chmod +x /app/scripts/*.py && airflow webserver"
    entrypoint: /bin/bash -c "/wait-for-it.sh postgres:5433 -- airflow webserver --port 8084"

  airflow-scheduler:
    image: apache/airflow:2.6.3
    container_name: airflow-scheduler
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_started
    env_file:
      - .env
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5433/airflow_db
      - AIRFLOW__CORE__FERNET_KEY=${AIRFLOW_FERNET_KEY}
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - PYTHONPATH=/opt/airflow

    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/scripts:/opt/airflow/scripts
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./wait-for-it.sh:/wait-for-it.sh

      # - ./scripts:/app
      # - ./db_config.py:/app/db_config.py
      - ./requirements.txt:/app/requirements.txt
    entrypoint: /bin/bash -c "/wait-for-it.sh postgres:5433 -- airflow scheduler"

volumes:
  pgdata:
  pgadmin_data:

networks:
  default:
    driver: bridge
